spring:
  application:
    name: notification
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/leetcode/protocol/openid-connect/certs

kafka:
  bootstrap-servers-config: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    prefer-ip-address: true
