apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start"]
          env:
            - name: KC_DB_URL_HOST
              value: "keycloak-database"
            - name: KC_DB_URL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: keycloak-db
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: keycloak-db-user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: keycloak-db-password
            - name: KC_HOSTNAME_URL
              value: "http://auth.localhost"
            - name: KC_HOSTNAME_ADMIN_URL # додай це — окремо для admin консолі
              value: "http://auth.localhost"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: keycloak-admin-username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: keycloak-admin-password
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000 # порт управління, а не основний
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
