apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Keycloak
  keycloak-url: "auth.localhost"
  keycloak-db: "keycloak"
  keycloak-db-user: "keycloak"
  keycloak-db-password: "secret"
  keycloak-admin-username: "admin"
  keycloak-admin-password: "admin"
  # Problem service
  problem-db: "problemdb"
  problem-db-user: "problem"
  problem-db-password: "secret"
  # Submission service
  submission-db: "submissiondb"
  submission-db-user: "submission"
  submission-db-password: "secret"