CREATE TABLE difficulty
(
    id         integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    difficulty character varying(24) NOT NULL
);

CREATE TABLE problem
(
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         text    NOT NULL,
    description   text    NOT NULL,
    difficulty_id integer NOT NULL REFERENCES difficulty (id),
    created_at    timestamp without time zone NOT NULL DEFAULT now(),
    updated_at    timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE tag
(
    id  integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tag character varying(24) NOT NULL
);

CREATE TABLE problem_tag
(
    problem_id integer NOT NULL REFERENCES problem (id),
    tag_id     integer NOT NULL REFERENCES tag (id)
);

CREATE TABLE testcase
(
    id           integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    problem_id   integer NOT NULL REFERENCES problem (id),
    storage_path text    NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now()
);
